const axios = require('axios');
const FormData = require('form-data');

// Retrieve credentials from environment variables to avoid hardcoding
const DIFY_API_KEY = process.env.DIFY_API_KEY;
const WHATSAPP_TOKEN = process.env.WHATSAPP_TOKEN;

module.exports = async (req, res) => {
    // ------------------ 1. Handle Meta Webhook Verification (GET) ------------------
    if (req.method === 'GET') {
        try {
            // Use WHATWG URL API to extract parameters accurately.
            // This fixes the missing req.query issue caused by the Node.js 24 runtime on Vercel.
            const myUrl = new URL(req.url, `https://${req.headers.host || 'localhost'}`);
            const mode = myUrl.searchParams.get('hub.mode');
            const token = myUrl.searchParams.get('hub.verify_token');
            const challenge = myUrl.searchParams.get('hub.challenge');

            console.log('--- Incoming Meta Verification Request --- mode:', mode, 'token:', token);

            // Hardcoded handshake check: must match "MY_CALORIE_BOT_VERIFY_TOKEN"
            if (mode === 'subscribe' && token === 'MY_CALORIE_BOT_VERIFY_TOKEN') {
                console.log('--- 🎉 Verification successful! Handshake complete. ---');
                return res.status(200).send(challenge);
            }

            console.log('--- ❌ Verification token mismatch ---');
            return res.status(403).send('Verification failed');
        } catch (urlError) {
            console.error('URL Parse Error:', urlError.message);
            return res.status(500).send('Internal Server Error');
        }
    }

    // ------------------ 2. Core Business Logic: Process Incoming Image Messages (POST) ------------------
    if (req.method === 'POST') {
        try {
            const entry = req.body?.entry?.[0];
            const changes = entry?.changes?.[0];
            const message = changes?.value?.messages?.[0];
            const phoneNumberId = changes?.value?.metadata?.phone_number_id;

            // If the incoming webhook is not an image message, acknowledge immediately and exit to prevent retries
            if (!message || message.type !== 'image' || !phoneNumberId) {
                return res.status(200).send('EVENT_RECEIVED');
            }

            const fromNumber = message.from; // User's WhatsApp phone number
            const imageId = message.image.id; // Image ID hosted on Meta's servers
            console.log(`📸【Captured successfully】A photo has been received from ${fromNumber} The photo ID is:: ${imageId}`);
            // Acknowledge Meta with a 200 OK immediately to prevent Vercel 504 timeouts during async processing
            res.status(200).send('EVENT_RECEIVED');

            // Push the workload into the background asynchronous pipeline
            await handleWorkflow(imageId, fromNumber, phoneNumberId);

        } catch (error) {
            console.error('Webhook Error:', error.message);
            if (!res.writableEnded) {
                res.status(200).send('EVENT_RECEIVED');
            }
        }
    }
};

// Asynchronous processing pipeline function
async function handleWorkflow(metaImageId, toPhoneNumber, phoneNumberId) {
    try {
        // Step 2.1: Retrieve the actual image download URL from Meta's servers
        const metaUrlRes = await axios.get(`https://graph.facebook.com/v19.0/${metaImageId}`, {
            headers: { 'Authorization': `Bearer ${WHATSAPP_TOKEN}` }
        });
        const downloadUrl = metaUrlRes.data.url;

        // Step 2.2: Download the binary stream of the image
        const imageStreamRes = await axios.get(downloadUrl, {
            headers: { 'Authorization': `Bearer ${WHATSAPP_TOKEN}` },
            responseType: 'arraybuffer'
        });
        const imageBuffer = Buffer.from(imageStreamRes.data);

        // Step 2.3: Wrap the image stream in FormData and upload it to Dify
        const form = new FormData();
        form.append('file', imageBuffer, { filename: 'food.jpg', contentType: 'image/jpeg' });
        form.append('user', 'abc');

        const difyUploadRes = await axios.post('https://api.dify.ai/v1/files/upload', form, {
            headers: {
                ...form.getHeaders(),
                'Authorization': `Bearer ${DIFY_API_KEY}`
            }
        });
        const difyFileId = difyUploadRes.data.id;

        // Step 2.4: Execute the Dify workflow in blocking mode with the file ID
        const difyWorkflowRes = await axios.post('https://api.dify.ai/v1/workflows/run', {
            response_mode: "blocking",
            user: "abc",
            inputs: { raw_id: difyFileId }
        }, {
            headers: {
                'Authorization': `Bearer ${DIFY_API_KEY}`,
                'Content-Type': 'application/json'
            }
        });

        // Extract the calorie breakdown text generated by the AI model
        const aiOutput = difyWorkflowRes.data.data.outputs.text;

        // Step 2.5: Append the Apple Health deep-link and reply back via WhatsApp
        const replyText = `${aiOutput}\n\n👉 [Click to log instantly in Apple Health](x-apple-health://DataPage/DietaryEnergy)`;
        
        await axios.post(`https://graph.facebook.com/v19.0/${phoneNumberId}/messages`, {
            messaging_product: "whatsapp",
            to: toPhoneNumber,
            type: "text",
            text: { body: replyText }
        }, {
            headers: { 'Authorization': `Bearer ${WHATSAPP_TOKEN}` }
        });

    } catch (err) {
        console.error('Processing Chain Failed:', err.response?.data || err.message);
    }
}