const axios = require('axios');
const FormData = require('form-data');

// Retrieve credentials from environment variables to avoid hardcoding
const DIFY_API_KEY = process.env.DIFY_API_KEY;
const WHATSAPP_TOKEN = process.env.WHATSAPP_TOKEN;

module.exports = async (req, res) => {
    // ------------------ 1. Handle initial Webhook verification from Meta (GET) ------------------
    if (req.method === 'GET') {
        const mode = req.query['hub.mode'];
        const token = req.query['hub.verify_token'];
        const challenge = req.query['hub.challenge'];

        // Custom verification token set to "MY_CALORIE_BOT_VERIFY_TOKEN"
        if (mode === 'subscribe' && token === 'MY_CALORIE_BOT_VERIFY_TOKEN') {
            return res.status(200).send(challenge);
        }
        return res.status(403).send('Verification failed');
    }

    // ------------------ 2. Core Business Logic: Handle incoming image messages (POST) ------------------
    if (req.method === 'POST') {
        try {
            const entry = req.body.entry?.[0];
            const changes = entry?.changes?.[0];
            const message = changes?.value?.messages?.[0];
            const phoneNumberId = changes?.value?.metadata?.phone_number_id;

            // If there is no message, or the message type is not an image, acknowledge and exit
            if (!message || message.type !== 'image' || !phoneNumberId) {
                return res.status(200).send('EVENT_RECEIVED');
            }

            const fromNumber = message.from; // User's WhatsApp phone number
            const imageId = message.image.id; // Image ID hosted on Meta's servers

            // Acknowledge Meta with a 200 OK immediately to prevent Vercel 504 timeouts during async processing
            res.status(200).send('EVENT_RECEIVED');

            // Start the sequential processing pipeline
            await handleWorkflow(imageId, fromNumber, phoneNumberId);

        } catch (error) {
            console.error('Webhook Error:', error.message);
            if (!res.writableEnded) {
                res.status(200).send('EVENT_RECEIVED');
            }
        }
    }
};

// Sequential pipeline processing function
async function handleWorkflow(metaImageId, toPhoneNumber, phoneNumberId) {
    try {
        // Step 2.1: Retrieve the actual image download URL from Meta's server
        const metaUrlRes = await axios.get(`https://graph.facebook.com/v19.0/${metaImageId}`, {
            headers: { 'Authorization': `Bearer ${WHATSAPP_TOKEN}` }
        });
        const downloadUrl = metaUrlRes.data.url;

        // Step 2.2: Download the binary stream of the image
        const imageStreamRes = await axios.get(downloadUrl, {
            headers: { 'Authorization': `Bearer ${WHATSAPP_TOKEN}` },
            responseType: 'arraybuffer'
        });
        const imageBuffer = Buffer.from(imageStreamRes.data);

        // Step 2.3: Wrap the image stream in FormData and upload it to Dify
        const form = new FormData();
        form.append('file', imageBuffer, { filename: 'food.jpg', contentType: 'image/jpeg' });
        form.append('user', 'abc');

        const difyUploadRes = await axios.post('https://api.dify.ai/v1/files/upload', form, {
            headers: {
                ...form.getHeaders(),
                'Authorization': `Bearer ${DIFY_API_KEY}`
            }
        });
        const difyFileId = difyUploadRes.data.id;

        // Step 2.4: Execute the Dify workflow with the clean file ID
        const difyWorkflowRes = await axios.post('https://api.dify.ai/v1/workflows/run', {
            response_mode: "blocking",
            user: "abc",
            inputs: { raw_id: difyFileId }
        }, {
            headers: {
                'Authorization': `Bearer ${DIFY_API_KEY}`,
                'Content-Type': 'application/json'
            }
        });

        // Extract the calorie breakdown text generated by Gemini
        const aiOutput = difyWorkflowRes.data.data.outputs.text;

        // Step 2.5: Construct the final payload with the Health App deep-link and reply via WhatsApp
        const replyText = `${aiOutput}\n\n👉 [Click to log instantly in Apple Health](x-apple-health://DataPage/DietaryEnergy)`;
        
        await axios.post(`https://graph.facebook.com/v19.0/${phoneNumberId}/messages`, {
            messaging_product: "whatsapp",
            to: toPhoneNumber,
            type: "text",
            text: { body: replyText }
        }, {
            headers: { 'Authorization': `Bearer ${WHATSAPP_TOKEN}` }
        });

    } catch (err) {
        console.error('Processing Chain Failed:', err.response?.data || err.message);
    }
}